#pragma once

#include "kernels/10_kernel_warptiling.cuh"
#include "kernels/11_kernel_double_buffering.cuh"
#include "kernels/12_kernel_double_buffering.cuh"
#include "kernels/1_naive.cuh"
#include "kernels/2_kernel_global_mem_coalesce.cuh"
#include "kernels/3_kernel_shared_mem_blocking.cuh"
#include "kernels/4_kernel_1D_blocktiling.cuh"
#include "kernels/5_kernel_2D_blocktiling.cuh"
#include "kernels/6_kernel_vectorize.cuh"
#include "kernels/7_kernel_resolve_bank_conflicts.cuh"
#include "kernels/8_kernel_bank_extra_col.cuh"
#include "kernels/9_kernel_autotuned.cuh"

#include "vector_kernels/101_naive.cuh"
#include "vector_kernels/102_warping.cuh"
#include "vector_kernels/103_preload.cuh"
#include "vector_kernels/104_preload2.cuh"
#include "vector_kernels/105_2D_blocktiling.cuh"
#include "vector_kernels/106_vec_mat_vectorized.cuh"
#include "vector_kernels/107_vec_mat_naive.cuh"
#include "vector_kernels/108_vec_mat_coalesced_warp_sgmev.cuh"
#include "vector_kernels/109_vec_mat_coalesced_warp_block.cuh"
